version: '2'

services: 
  app:
    image: 'scme/messenger:v1.0.0'
    container_name: app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/scme
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
          
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    ports:
      - "9090:5432"
    environment:
      - POSTGRES_DB=scme
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      